86cugexhf/landing page
nijin-26/bus-ticket-booking-react pull request #20
Opened 2024-02-09 03:53 UTC by sania-salim

### Description
This branch contains landing page UI.

### Changes made
1. Action bar incorporated with PNR search tab switching, appropriate dimension changes.
2. Illustration for dark theme and light theme.
3. Routing to listing page.
4. Multilingual support incorporated for heading in landing page.

2024-02-09 05:24 UTC, akshay-krishna requested changes

2024-02-09 05:24 UTC, akshay-krishna commented on src/components/actionBar/actionBar/ActionBar.tsx
> -                <Stack spacing={0} width="1000px" direction="row">
Better to convert width to rem

2024-02-09 05:24 UTC, akshay-krishna commented on src/pages/LandingPage/LandingPage.styled.ts
> +export const LandingPageWrapper = styled.section`
Couldnt you use styled component from MUI (@emotion/styled) rather than from styled-components

2024-02-09 07:03 UTC, RJR-003 requested changes

2024-02-09 07:03 UTC, RJR-003 commented on src/components/actionBar/actionBarTab/ActionBarTab.styled.ts
> +    min-width: 120rem;
The action bar needs appropriate padding.

2024-02-09 07:03 UTC, RJR-003 commented on src/components/actionBar/actionBarTab/ActionBarTab.styled.ts
You could use percentage values for width instead of hard coding it.

2024-02-12 04:11 UTC, RJR-003 approved these changes

2024-02-14 11:14 UTC, akshay-krishna commented on src/components/actionBar/sortFilterRadioGroups/SortGroup.tsx
> +        <>
Is this fragment necessary

2024-02-14 11:14 UTC, akshay-krishna commented on src/components/actionBar/filterSort/FilterSort.tsx
>          <>
Is fragment necessary?

2024-02-14 11:14 UTC, akshay-krishna commented on src/components/actionBar/actionBar/ActionBar.tsx
> +                                height: '40px',
Use rem instead of px

2024-02-14 11:14 UTC, akshay-krishna commented on src/components/actionBar/actionBarDrawer/ActionBarDrawerStyled.tsx
> +    fontSize: 20,
Use fontSize from theme.ts

2024-02-14 11:14 UTC, akshay-krishna commented on src/components/actionBar/actionBarDrawer/ActionBarDrawerStyled.tsx
> +    fontSize: 16,
Use fontSize from theme.ts

2024-02-15 03:54 UTC, akshay-krishna approved these changes

2024-02-15 04:25 UTC, RJR-003 approved these changes

2024-02-15 04:25 UTC, RJR-003 commented on src/components/actionBar/actionBar/ActionBar.tsx
> +    // People,
remove unwanted elements and comments

2024-02-15 07:33 UTC, merged