86cuewym2/Redux - with theme slice.
nijin-26/bus-ticket-booking-react pull request #9
Opened 2024-02-01 17:37 UTC by nijin-26

### Summary:
Developers can now use the custom hooks useAppSelector and useAppDispatch for simplified access to the Redux store. The themeSlice can be utilized for managing and updating the application theme.

### Changes:

1. Redux Store Setup: A Redux store has been configured using @reduxjs/toolkit. The store includes a slice for managing the application theme.

2. ThemeSlice: A themeSlice has been added to handle actions related to theme switching. It includes the ability to toggle between light and dark themes and set a specific theme.

3. Custom Hooks for Selector and Dispatch: Custom hooks have been created to simplify the usage of useSelector and useDispatch throughout the application, providing a cleaner and more organized way to interact with the Redux store.

2024-02-01 17:58 UTC, abhijith-biju commented on src/app/features/themeSlice.ts
> +interface ThemeState {
prefixing interfaces with I would be better as that convention followed for other interfaces.

2024-02-01 18:02 UTC, abhijith-biju commented on src/app/store.ts
> +// Inferred type: {posts: PostsState, comments: CommentsState, users: UsersState}
Comment specifies incorrect inferred type. 
Is this comment necessary as more slices can be added to the store in future?

2024-02-01 18:11 UTC, abhijith-biju commented on src/app/hook.ts
How about hooks.ts as the file name?

2024-02-01 18:12 UTC, abhijith-biju requested changes
Please look into the comments.

2024-02-02 02:12 UTC, nijin-26 commented
> Please look into the comments.

All of those comments are resolved in the recent commit.

2024-02-02 02:14 UTC, nijin-26 commented on src/app/hook.ts
Yes. It's better. I have updated it.

2024-02-02 04:27 UTC, amaljoeqb approved these changes

2024-02-02 05:47 UTC, abhijith-biju approved these changes

2024-02-02 05:49 UTC, seraGeorge approved these changes

2024-02-02 10:49 UTC, lekshmi615213 commented on src/app/features/themeSlice.ts
> +    currentTheme: 'light' | 'dark';
enum ?

2024-02-02 11:31 UTC, nijin-26 commented on src/app/features/themeSlice.ts
> +    currentTheme: 'light' | 'dark';
I have updated it in the recent commit.

2024-02-02 11:31 UTC, merged